version: '2.1'
services:
    webserver:
        image: registry.akulaku.com/data/airflow:v2.6.0-python3.10
        restart: always
        volumes:
            - ./dags:/opt/airflow/dags
            - ./plugins:/opt/airflow/plugins
            - ./logs:/opt/airflow/logs
            - ./config/airflow.cfg:/opt/airflow/airflow.cfg
        ports:
            - "8080:8080"
        environment:
            - LANDSAT_SQL_ALCHEMY_CONN=${LANDSAT_SQL_ALCHEMY_CONN}
        command: ["airflow", "webserver"]
    scheduler:
        image: registry.akulaku.com/data/airflow:v2.6.0-python3.10
        restart: always
        volumes:
            # dag and plugins
            - ./dags:/opt/airflow/dags
            - ./plugins:/opt/airflow/plugins
            - ./logs:/opt/airflow/logs
            - ./config/airflow.cfg:/opt/airflow/airflow.cfg
        environment:
            - LANDSAT_SQL_ALCHEMY_CONN=${LANDSAT_SQL_ALCHEMY_CONN}
        command: ["airflow", "scheduler"]
    flower:
        image: registry.akulaku.com/data/airflow:v2.6.0-python3.10
        restart: always
        volumes:
            - ./dags:/opt/airflow/dags
            - ./plugins:/opt/airflow/plugins
            - ./logs:/opt/airflow/logs
            - ./config/airflow.cfg:/opt/airflow/airflow.cfg
        ports:
            - "5555:5555"
        command: ["airflow", "celery", "flower"]
    worker:
        image: registry.akulaku.com/data/airflow:v2.6.0-python3.10
        restart: always
        volumes:
            - ./dags:/opt/airflow/dags
            - ./plugins:/opt/airflow/plugins
            - ./logs:/opt/airflow/logs
            - ./config/airflow.cfg:/opt/airflow/airflow.cfg
        ports:
            - "8793:8793"
        environment:
            - LANDSAT_SQL_ALCHEMY_CONN=${LANDSAT_SQL_ALCHEMY_CONN}
        command: ["airflow", "celery", "worker"]
    restApi:
        image: registry.akulaku.com/data/airflow:v2.6.0-python3.10
        restart: always
        volumes:
            - ./dags:/opt/airflow/dags
            - ./plugins:/opt/airflow/plugins
            - ./logs:/opt/airflow/logs
            - ./config/airflow.cfg:/opt/airflow/airflow.cfg
        ports:
            - "8090:8090"
        environment:
            - LANDSAT_SQL_ALCHEMY_CONN=${LANDSAT_SQL_ALCHEMY_CONN}
        entrypoint: ["/bin/bash", "/opt/airflow/plugins/rest_api/start.sh"]