apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # The sql_alchemy_conn value is a base64 encoded representation of this connection string:
  # postgresql+psycopg2://root:root@postgres-airflow:5432/airflow
  sql_alchemy_conn: base64=
  landsat_sql_alchemy_conn: base64=
  broker_url: base64=
  result_backend: base64=