# 将 PersistentVolume 中的 server 和 path 替换为已有的 NFS 服务器地址和挂载路径

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  labels:
    pv: airflow-dags-pv
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /data/nfs/airflow-dags/
    server: 192.168.146.189

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      pv: airflow-dags-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  labels:
    pv: airflow-logs-pv
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /data/nfs/airflow-logs/
    server: 192.168.146.189

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      pv: airflow-logs-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-plugins-pv
  labels:
    pv: airflow-plugins-pv
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /data/nfs/airflow-plugins/
    server: 192.168.146.189

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-plugins-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      pv: airflow-plugins-pv
